### ISSUE TITLE
milestones requires more user input

### ISSUE THREAD

**Issue by logzinga** [OwOCraft/owocraft-website#6]
to actually write the milestones i need A LOT more user input

help wanted asap

**Comment by logzinga** [comment]
if you want to help with milestones reply to this issue

**Comment by logzinga** [comment]
maybe once we build a bank we can get the economy

like a big bank, one to look cool and badass

**Comment by RainbowTilleh** [comment]
absolutely extravagant idea

**Comment by logzinga** [comment]
alright, i'll add it

**Comment by RainbowTilleh** [comment]
I think we should list the plugins and then write ways we can use them as milestones.

**Comment by logzinga** [comment]
okay yeah let me do that

**Comment by logzinga** [comment]
essentials plugin includes warps economy and some other server command stuff so it will be seperate

**Comment by RainbowTilleh** [comment]
Could that be a milestone that includes doing multiple things?

**Comment by logzinga** [comment]
warp
home
economy
tpa
imagemap
prison (jail)

**Comment by logzinga** [comment]
> Could that be a milestone that includes doing multiple things?

oh yes def
will be utilised

**Comment by RainbowTilleh** [comment]
Lets start with warps. What warps will be available?

**Comment by logzinga** [comment]
> warp home economy tpa imagemap prison (jail)

there are some others but I will work on those later

**Comment by logzinga** [comment]
earned as in deserved to the players

**Comment by logzinga** [comment]
imagemap,,,,,

i guess maybe an art gallery? or a place where you can create them idk actually

**Comment by RainbowTilleh** [comment]
The milestone could be something like building a statue? Perhaps the logzinga statue orrr technoblade one we had last season? It could also be a decorative town centre, a piece of art in some way?

**Comment by logzinga** [comment]
i dont think so (statue), it doesnt seem like building a statue can get us to make and use images

**Comment by RainbowTilleh** [comment]
It's kinda the idea of art. An art gallery, like you said, could be good. It could only be complete when server members make art in it, then they get image maps.. maybeeee

**Comment by logzinga** [comment]
i do aswell

**Comment by logzinga** [comment]
but im not sure how players can create art exactly

**Comment by logzinga** [comment]
without im

**Comment by RainbowTilleh** [comment]
> but im not sure how players can create art exactly

Thats the funny part

**Comment by logzinga** [comment]
...right

**Comment by logzinga** [comment]
i mean, this art gallery would have to be MASSIVE

**Comment by RainbowTilleh** [comment]
I can just see absolute chaos of art.

**Comment by logzinga** [comment]
for multiple exhibitions and unique works of art

**Comment by logzinga** [comment]
i guess it could work, may need more consideration

imagemaps require more thought and consideration

**Comment by logzinga** [comment]
what about discord

**Comment by RainbowTilleh** [comment]
Well there could be limited spaces for artworks, as in a certain amount of art spots avalible before they run out. It could also have size limits on the art. Im not talking massive statues or anything. The gallery could be a way for people to show they have been there and show ppl how epic they are at art.

**Comment by logzinga** [comment]
> Well there could be limited spaces for artworks, as in a certain amount of art spots avalible before they run out. It could also have size limits on the art. Im not talking massive statues or anything. The gallery could be a way for people to show they have been there and show ppl how epic they are at art.

yeah ig
I'll think about it more later

**Comment by RainbowTilleh** [comment]
So what about discord..?

**Comment by logzinga** [comment]
yk the discord bot?

**Comment by logzinga** [comment]
its a plugin

**Comment by RainbowTilleh** [comment]
Ah yes. You want that as a milestone?

**Comment by logzinga** [comment]
yeah, maybe a communications tower

**Comment by logzinga** [comment]
> yeah, maybe a communications tower

could also unlock prox chat

**Comment by RainbowTilleh** [comment]
Smart

**Comment by logzinga** [comment]
yeah okay

+1 discord and prox chat unlocked by communications tower

**Comment by RainbowTilleh** [comment]
I was thinking a milestone for prox chat but it would be much funnier if we just had it at the start, where there are no rules and chaos runs havoc

**Comment by RainbowTilleh** [comment]
yipee

**Comment by RainbowTilleh** [comment]
Prison is easy, build a prison. But we could also have to build a police station or establish some sort of law enforcement.

**Comment by logzinga** [comment]
yeah fair enough

**Comment by RainbowTilleh** [comment]
Next, home plugin... or would that go with the warps?

**Comment by logzinga** [comment]
home plugin should be easier than warps

**Comment by RainbowTilleh** [comment]
Okay well then what would be the milestone

**Comment by logzinga** [comment]
maybe, would it have to be big and look really good in the city?

**Comment by RainbowTilleh** [comment]
Yeah seems alright. Unless we find something better

**Comment by RainbowTilleh** [comment]
What are we gonna do for tpa?

**Comment by RainbowTilleh** [comment]
Maybeee a hall of fame thing with every players names

**Comment by logzinga** [comment]
yeah seems good with me

**Comment by logzinga** [comment]
like, a good hall of names

**Comment by logzinga** [comment]
+1 Hall of Names = /tpa

**Comment by RainbowTilleh** [comment]
I think that's all... Apart from the other plugins that weren't listed.

**Comment by logzinga** [comment]
closing until we have more plugins

**Comment by logzinga** [comment]
speaking of which, we require a milestone for the /warp command

**Comment by RainbowTilleh** [comment]
So we are having the warp command?

**Comment by RainbowTilleh** [comment]
A milestone for the warps could be a form of transportation, for example, getting elytra's, horse/car shop or building a subway.

**Comment by logzinga** [comment]
we need to have server wide transportation, free of charge. something like a train station but maybe also adding a subway station as well

**Comment by logzinga** [comment]
or we require both an airport and a train station

**Comment by logzinga** [comment]
it's gotta be hard to get

**Comment by RainbowTilleh** [comment]
The milestone could just be roads and paths everywhere, or a train station like you said.

**Comment by logzinga** [comment]
roads anyone can do, we need something for faster and direct transportation

**Comment by RainbowTilleh** [comment]
so a train track or subway?

**Comment by logzinga** [comment]
and maybe an airport

**Comment by logzinga** [comment]
we still need help with the /warp command milestone

**Comment by CruzoPlayz** [comment]
> we still need help with the /warp command milestone

hello perhaps we should have a main hub/hub building so we can /warp to it

**Comment by logzinga** [comment]
we could do that, not sure how it should look n such but we could do something like that

**Comment by logzinga** [comment]
we also need to start working on the milestone for the owocraft map (primary server dynmap)

**Comment by RainbowTilleh** [comment]
hmm that's a tricky one. Could the warp command be an airport? I feel like we have already been over this but I dont remember why it isn't..

**Comment by logzinga** [comment]
in general while an airport ((could)) work, i think that the airport could be utilised for something else entirely

**Comment by RainbowTilleh** [comment]
Like what? I already have a massive airport design that is also the communications tower for that milestone, it would be nice to check two boxes off at once.

**Comment by CruzoPlayz** [comment]
Yes 2 at once is cool

**Comment by logzinga** [comment]
not doing milestones anymore.
